CREATE TABLE person(
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                       name VARCHAR,
                       cell_number VARCHAR NOT NULL UNIQUE,
                       role VARCHAR not null ,
                       is_verified BOOLEAN DEFAULT FALSE
);
CREATE TABLE type(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     type VARCHAR NOT NULL
);
CREATE TABLE product(
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR NOT NULL,
                        description VARCHAR NOT NULL ,
                        price DECIMAL NOT NULL,
                        type_id INT REFERENCES type(id),
                        image_url VARCHAR NOT NULL,
                        discount INT NOT NULL,
                        is_available BOOLEAN DEFAULT TRUE
);

CREATE TABLE promotions(
                           id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           title VARCHAR NOT NULL,
                           description TEXT NOT NULL,
                           image_url VARCHAR NOT NULL
);
CREATE TABLE cart(
                     id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     person_id INT REFERENCES person(id) NOT NULL,
                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE cart_item(
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          cart_id INT REFERENCES cart(id) NOT NULL,
                          product_id INT REFERENCES product(id) NOT NULL,
                          quantity INT NOT NULL DEFAULT 1
);
